[package]
name = "multiboot2-host"
version = "0.1.1"
authors = ["The0x539"]
edition = "2018"
license = "Apache-2.0"
description = "An experimental Multiboot2 crate for VM hosts."

[features]
hvm = []

[dependencies]
byteorder = "1"
num_enum = "0.5.1"
thiserror = "1.0.21"
